#!/bin/bash

# ============================================================
# Research Gateway Linux
# AD Join + SSSD + DCV Password Authentication Bootstrap
#
# Amazon Linux 2023
#
# This script:
#
#   1. Configures persistent AD DNS
#   2. Installs AD/SSSD/DCV authentication dependencies
#   3. Validates AD DNS / Kerberos / LDAP
#   4. Joins the instance to Active Directory
#   5. Configures SSSD
#   6. Enables automatic home directory creation
#   7. Creates custom DCV PAM configuration
#   8. Configures DCV to use system authentication
#   9. Allows DCV service account to communicate with SSSD
#  10. Restarts SSSD and DCV
#  11. Performs validation
#
# AD join credentials are retrieved from AWS Secrets Manager.
# The secret contains:
#
# {
#   "username": "admin",
#   "password": "..."
# }
#
# The password is not stored in this script.
# ============================================================

set -u

# ============================================================
# LOGGING
# ============================================================

LOG_DIR="/var/log/rg-ad-bootstrap"
LOG_FILE="${LOG_DIR}/ad-join.log"
STATUS_FILE="${LOG_DIR}/status"

mkdir -p "${LOG_DIR}"
chmod 700 "${LOG_DIR}"

exec > >(tee -a "${LOG_FILE}") 2>&1

echo "============================================================"
echo "RG Linux AD + DCV Authentication Bootstrap"
echo "Started: $(date)"
echo "============================================================"

# ============================================================
# CONFIGURATION
# ============================================================

AD_DOMAIN="corp.quantum.com"
AD_REALM="CORP.QUANTUM.COM"

AD_DNS_1="10.0.0.14"
AD_DNS_2="10.0.0.91"

AD_SECRET_NAME="/rg/ad/domain-join"

INTERFACE="ens5"

NETWORK_DROPIN_DIR="/etc/systemd/network/70-ens5.network.d"
NETWORK_DROPIN="${NETWORK_DROPIN_DIR}/10-ad-dns.conf"

DCV_PAM_FILE="/etc/pam.d/dcv.custom"
DCV_CONFIG="/etc/dcv/dcv.conf"
DCV_SESSION_MANAGER="/usr/local/sbin/dcv-session-manager"
DCV_SESSION_LOG="/var/log/dcv-rg-session.log"

# ============================================================
# ERROR HANDLER
# ============================================================

fail()
{
    local MESSAGE="$1"

    echo ""
    echo "============================================================"
    echo "AD BOOTSTRAP FAILED"
    echo "============================================================"
    echo "Reason: ${MESSAGE}"
    echo "Time: $(date)"
    echo "Log: ${LOG_FILE}"
    echo "============================================================"

    printf 'FAILED\n%s\n' "${MESSAGE}" > "${STATUS_FILE}"

    exit 1
}

# ============================================================
# STEP 1 - BASIC SYSTEM INFORMATION
# ============================================================

echo ""
echo "============================================================"
echo "STEP 1 - SYSTEM INFORMATION"
echo "============================================================"

hostname
cat /etc/os-release
uname -r

echo ""
echo "Network interface:"
ip addr show "${INTERFACE}" || true

# ============================================================
# STEP 2 - INSTALL REQUIRED PACKAGES
# ============================================================

echo ""
echo "============================================================"
echo "STEP 2 - INSTALLING REQUIRED PACKAGES"
echo "============================================================"

dnf install -y \
    realmd \
    sssd \
    adcli \
    oddjob \
    oddjob-mkhomedir \
    samba-common-tools \
    krb5-workstation \
    bind-utils \
    nc \
    awscli \
    jq \
    || fail "Required package installation failed."

echo "Packages installed successfully."

# ============================================================
# STEP 3 - CONFIGURE PERSISTENT AD DNS
#
# Amazon Linux 2023 uses systemd-networkd.
#
# We deliberately do NOT modify:
#
#   /run/systemd/network/70-ens5.network
#
# because that file is generated by amazon-ec2-net-utils.
#
# Instead we create a persistent drop-in.
# ============================================================

echo ""
echo "============================================================"
echo "STEP 3 - CONFIGURING AD DNS"
echo "============================================================"

mkdir -p "${NETWORK_DROPIN_DIR}"

cat > "${NETWORK_DROPIN}" <<EOF
[Network]
DNS=${AD_DNS_1}
DNS=${AD_DNS_2}

[DHCPv4]
UseDNS=no
EOF

chmod 644 "${NETWORK_DROPIN}"

echo "Created:"
cat "${NETWORK_DROPIN}"

# ============================================================
# STEP 4 - RELOAD NETWORK
# ============================================================

echo ""
echo "============================================================"
echo "STEP 4 - RELOADING NETWORK CONFIGURATION"
echo "============================================================"

networkctl reload || fail "networkctl reload failed."

sleep 2

networkctl reconfigure "${INTERFACE}" || \
    fail "Unable to reconfigure ${INTERFACE}."

sleep 5

echo ""
echo "Resolver configuration:"
resolvectl status "${INTERFACE}" || true

# ============================================================
# STEP 5 - DNS CONNECTIVITY
# ============================================================

echo ""
echo "============================================================"
echo "STEP 5 - TESTING AD DNS CONNECTIVITY"
echo "============================================================"

nc -z -w 5 "${AD_DNS_1}" 53 || \
    fail "Cannot reach AD DNS ${AD_DNS_1}:53"

nc -z -w 5 "${AD_DNS_2}" 53 || \
    fail "Cannot reach AD DNS ${AD_DNS_2}:53"

echo "Both AD DNS servers are reachable."

# ============================================================
# STEP 6 - WAIT FOR AD DNS
# ============================================================

echo ""
echo "============================================================"
echo "STEP 6 - VALIDATING AD DNS"
echo "============================================================"

MAX_ATTEMPTS=30
ATTEMPT=1

while [ "${ATTEMPT}" -le "${MAX_ATTEMPTS}" ]; do

    echo "DNS validation attempt ${ATTEMPT}/${MAX_ATTEMPTS}"

    if nslookup "${AD_DOMAIN}" "${AD_DNS_1}" >/dev/null 2>&1 && \
       nslookup "${AD_DOMAIN}" "${AD_DNS_2}" >/dev/null 2>&1; then

        echo "AD domain DNS resolution successful."
        break
    fi

    if [ "${ATTEMPT}" -eq "${MAX_ATTEMPTS}" ]; then
        fail "AD domain DNS resolution failed."
    fi

    sleep 5
    ATTEMPT=$((ATTEMPT + 1))

done

echo ""
echo "AD domain:"
nslookup "${AD_DOMAIN}"

# ============================================================
# STEP 7 - KERBEROS SRV VALIDATION
# ============================================================

echo ""
echo "============================================================"
echo "STEP 7 - VALIDATING KERBEROS SRV"
echo "============================================================"

KERBEROS_SRV=$(dig +short SRV "_kerberos._tcp.${AD_DOMAIN}")

echo "${KERBEROS_SRV}"

[ -n "${KERBEROS_SRV}" ] || \
    fail "Kerberos SRV record not found."

# ============================================================
# STEP 8 - LDAP SRV VALIDATION
# ============================================================

echo ""
echo "============================================================"
echo "STEP 8 - VALIDATING LDAP SRV"
echo "============================================================"

LDAP_SRV=$(dig +short SRV "_ldap._tcp.${AD_DOMAIN}")

echo "${LDAP_SRV}"

[ -n "${LDAP_SRV}" ] || \
    fail "LDAP SRV record not found."

# ============================================================
# STEP 9 - REALM DISCOVERY
# ============================================================

echo ""
echo "============================================================"
echo "STEP 9 - AD REALM DISCOVERY"
echo "============================================================"

realm discover "${AD_DOMAIN}" || \
    fail "realm discover failed."

# ============================================================
# STEP 10 - CHECK DOMAIN MEMBERSHIP
# ============================================================

echo ""
echo "============================================================"
echo "STEP 10 - CHECKING DOMAIN MEMBERSHIP"
echo "============================================================"

if realm list | grep -qi "^${AD_DOMAIN}$"; then

    echo "Instance is already joined to ${AD_DOMAIN}."

    ALREADY_JOINED="yes"

else

    echo "Instance is not currently joined."

    ALREADY_JOINED="no"

fi

# ============================================================
# STEP 11 - RETRIEVE AD JOIN CREDENTIALS
#
# Credentials are stored in AWS Secrets Manager as:
#
# {
#   "username": "admin",
#   "password": "..."
# }
#
# The password is never intentionally written to the log.
# ============================================================

if [ "${ALREADY_JOINED}" = "no" ]; then

    echo ""
    echo "============================================================"
    echo "STEP 11 - RETRIEVING AD JOIN PASSWORD"
    echo "============================================================"

    AD_CREDENTIALS=$(aws secretsmanager get-secret-value \
        --secret-id "${AD_SECRET_NAME}" \
        --region "${AWS_REGION}" \
        --query 'SecretString' \
        --output text) || \
        fail "Unable to retrieve AD join credentials from Secrets Manager."

    if [ -z "${AD_CREDENTIALS}" ] || [ "${AD_CREDENTIALS}" = "None" ]; then
        unset AD_CREDENTIALS
        fail "Secrets Manager returned an empty secret."
    fi

    AD_JOIN_USER=$(printf '%s' "${AD_CREDENTIALS}" | jq -r '.username')
    AD_PASSWORD=$(printf '%s' "${AD_CREDENTIALS}" | jq -r '.password')

    unset AD_CREDENTIALS

    if [ -z "${AD_JOIN_USER}" ] || [ "${AD_JOIN_USER}" = "null" ]; then
        unset AD_PASSWORD
        fail "Secrets Manager secret does not contain a valid username."
    fi

    if [ -z "${AD_PASSWORD}" ] || [ "${AD_PASSWORD}" = "null" ]; then
        unset AD_PASSWORD
        fail "Secrets Manager secret does not contain a valid password."
    fi

    echo "AD join credential retrieved successfully."
    echo "AD join user: ${AD_JOIN_USER}"

    # ========================================================
    # STEP 12 - JOIN ACTIVE DIRECTORY
    # ========================================================

    echo ""
    echo "============================================================"
    echo "STEP 12 - JOINING ACTIVE DIRECTORY"
    echo "============================================================"

    printf '%s\n' "${AD_PASSWORD}" | \
        realm join \
        --verbose \
        --user="${AD_JOIN_USER}" \
        "${AD_DOMAIN}"

    JOIN_RC=$?

    # Immediately remove password from shell memory.
    unset AD_PASSWORD

    if [ "${JOIN_RC}" -ne 0 ]; then
        fail "Active Directory join failed."
    fi

    echo "Active Directory join successful."

else

    echo "Skipping realm join because instance is already joined."

fi

# ============================================================
# STEP 13 - VERIFY REALM
# ============================================================

echo ""
echo "============================================================"
echo "STEP 13 - VERIFYING AD MEMBERSHIP"
echo "============================================================"

realm list

realm list | grep -qi "^${AD_DOMAIN}$" || \
    fail "AD realm membership verification failed."

echo "AD membership verified."

# ============================================================
# STEP 14 - VERIFY KEYTAB
# ============================================================

echo ""
echo "============================================================"
echo "STEP 14 - VERIFYING KERBEROS KEYTAB"
echo "============================================================"

[ -f /etc/krb5.keytab ] || \
    fail "/etc/krb5.keytab does not exist."

klist -k /etc/krb5.keytab || \
    fail "Unable to read /etc/krb5.keytab."

# ============================================================
# STEP 15 - BACKUP EXISTING SSSD CONFIG
# ============================================================

echo ""
echo "============================================================"
echo "STEP 15 - CONFIGURING SSSD"
echo "============================================================"

if [ -f /etc/sssd/sssd.conf ]; then

    if [ ! -f /etc/sssd/sssd.conf.before-rg-ad-bootstrap ]; then

        cp /etc/sssd/sssd.conf \
           /etc/sssd/sssd.conf.before-rg-ad-bootstrap

        echo "Existing SSSD configuration backed up."

    fi

fi

# ============================================================
# STEP 16 - CREATE SSSD CONFIG
#
# Based on the configuration in the provided DCV document:
#
# allowed_uids = root, dcv
# access_provider = simple
#
# ============================================================

cat > /etc/sssd/sssd.conf <<EOF
[sssd]
domains = ${AD_DOMAIN}
config_file_version = 2
services = nss, pam
allowed_uids = root, dcv

[domain/${AD_DOMAIN}]
default_shell = /bin/bash
krb5_store_password_if_offline = True
cache_credentials = True
krb5_realm = ${AD_REALM}
realmd_tags = manages-system joined-with-adcli
id_provider = ad
fallback_homedir = /home/%u
ad_domain = ${AD_DOMAIN}
use_fully_qualified_names = False
ldap_id_mapping = True
access_provider = simple
EOF

chmod 600 /etc/sssd/sssd.conf
chown root:root /etc/sssd/sssd.conf

echo "SSSD configuration:"
cat /etc/sssd/sssd.conf

# ============================================================
# STEP 17 - CONFIGURE AUTHSELECT / MKHOMEDIR
# ============================================================

echo ""
echo "============================================================"
echo "STEP 17 - CONFIGURING AUTOMATIC HOME DIRECTORIES"
echo "============================================================"

authselect select sssd with-mkhomedir --force || \
    fail "authselect configuration failed."

# ============================================================
# STEP 18 - ENABLE ODDJOB + SSSD
# ============================================================

echo ""
echo "============================================================"
echo "STEP 18 - STARTING SSSD / ODDJOB"
echo "============================================================"

systemctl enable --now oddjobd || \
    fail "Unable to start oddjobd."

systemctl enable --now sssd || \
    fail "Unable to start SSSD."

systemctl restart sssd || \
    fail "Unable to restart SSSD."

systemctl is-active --quiet sssd || \
    fail "SSSD is not active."

echo "SSSD is active."

# ============================================================
# STEP 19 - INSTALL DCV SESSION MANAGER
#
# The session manager is invoked by PAM during DCV authentication.
# It ensures that the fixed virtual session "rg-session" is owned by
# the authenticated AD user.  If another user owns the session, the
# existing session is closed and recreated for the authenticated user.
#
# No DCV session is created at boot.  The first authenticated user
# creates the session on demand.
# ============================================================

echo ""
echo "============================================================"
echo "STEP 19 - INSTALLING DCV SESSION MANAGER"
echo "============================================================"

cat > "${DCV_SESSION_MANAGER}" <<'EOF'
#!/bin/bash

SESSION="rg-session"
LOG="/var/log/dcv-rg-session.log"
DCV_BIN="/usr/bin/dcv"
USER_NAME="${PAM_USER:-}"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S %Z')] $*" >> "$LOG"
}

log "PAM_USER=${USER_NAME:-<none>} PAM_SERVICE=${PAM_SERVICE:-<none>} PAM_TYPE=${PAM_TYPE:-<none>}"

# Execute only during authentication.
if [[ "${PAM_TYPE:-}" != "auth" ]]; then
    exit 0
fi

# PAM_USER must exist.
if [[ -z "$USER_NAME" ]]; then
    log "ERROR=missing-PAM_USER"
    exit 0
fi

# Allow only expected Linux / AD usernames.
if [[ ! "$USER_NAME" =~ ^[A-Za-z0-9._-]+$ ]]; then
    log "ERROR=invalid-PAM_USER"
    exit 0
fi

# Verify DCV CLI exists.
if [[ ! -x "$DCV_BIN" ]]; then
    log "ERROR=dcv-command-not-found:$DCV_BIN"
    exit 0
fi

# Determine current owner of rg-session.
CURRENT_OWNER="$($DCV_BIN list-sessions 2>/dev/null |
    sed -n "s/^Session: '$SESSION'.*(owner:\([^ ]*\).*/\1/p")"

log "CURRENT_OWNER=${CURRENT_OWNER:-<none>}"

# Already owned by authenticated user.
if [[ "$CURRENT_OWNER" == "$USER_NAME" ]]; then
    log "ACTION=already-owned-by-$USER_NAME"
    exit 0
fi

# Another user owns the session.
if [[ -n "$CURRENT_OWNER" ]]; then
    log "ACTION=close-session-owner-$CURRENT_OWNER"

    if ! $DCV_BIN close-session "$SESSION" >> "$LOG" 2>&1; then
        log "ERROR=close-session-failed"
        exit 0
    fi

    for i in {1..20}; do
        if ! $DCV_BIN list-sessions 2>/dev/null |
             grep -q "^Session: '$SESSION'"; then
            break
        fi
        sleep 0.25
    done

    if $DCV_BIN list-sessions 2>/dev/null |
       grep -q "^Session: '$SESSION'"; then
        log "ERROR=session-still-exists-after-close"
        exit 0
    fi
fi

# Create session for authenticated user.
log "ACTION=create-session-user-$USER_NAME"

$DCV_BIN create-session "$SESSION" \
    --name "$SESSION" \
    --type virtual \
    --user "$USER_NAME" \
    --owner "$USER_NAME" >> "$LOG" 2>&1

CREATE_RC=$?

log "CREATE_RC=$CREATE_RC"

if [[ "$CREATE_RC" -eq 0 ]]; then
    log "ACTION=create-success"
else
    log "ACTION=create-failed"
fi

exit 0
EOF

chmod 755 "${DCV_SESSION_MANAGER}"
chown root:root "${DCV_SESSION_MANAGER}"

install -o root -g root -m 600 /dev/null "${DCV_SESSION_LOG}"

[ -x "${DCV_SESSION_MANAGER}" ] ||     fail "Unable to install DCV session manager."

[ -f "${DCV_SESSION_LOG}" ] ||     fail "Unable to create DCV session manager log."

echo "DCV session manager:"
ls -l "${DCV_SESSION_MANAGER}"
echo "DCV session manager log:"
ls -l "${DCV_SESSION_LOG}"

# ============================================================
# STEP 20 - CREATE CUSTOM DCV PAM PROFILE
#
# Authentication uses the Linux system PAM stack and invokes the
# DCV session manager during the auth phase.  The manager is optional
# from PAM's perspective so a manager error does not itself cause a
# PAM authentication failure.
# ============================================================

echo ""
echo "============================================================"
echo "STEP 20 - CONFIGURING DCV CUSTOM PAM"
echo "============================================================"

cat > "${DCV_PAM_FILE}" <<'EOF'
#%PAM-1.0

auth        required      pam_env.so
auth        substack      system-auth
auth        optional      pam_exec.so seteuid /usr/local/sbin/dcv-session-manager

account     required      pam_permit.so
account     include       system-auth

session     required      pam_selinux.so open
session     include       system-auth
EOF

chmod 644 "${DCV_PAM_FILE}"
chown root:root "${DCV_PAM_FILE}"

echo "Created:"
cat "${DCV_PAM_FILE}"

# ============================================================
# STEP 21 - CONFIGURE DCV
#
# The attached document specifies:
#
# [security]
# authentication="system"
# pam-service-name="dcv.custom"
#
# We preserve other existing dcv.conf content.
# ============================================================

echo ""
echo "============================================================"
echo "STEP 21 - CONFIGURING DCV SYSTEM AUTHENTICATION"
echo "============================================================"

[ -f "${DCV_CONFIG}" ] || \
    fail "${DCV_CONFIG} does not exist."

if [ ! -f "${DCV_CONFIG}.before-rg-ad-bootstrap" ]; then

    cp "${DCV_CONFIG}" \
       "${DCV_CONFIG}.before-rg-ad-bootstrap"

    echo "Original DCV configuration backed up."

fi

# Remove an existing [security] block if present.
# This avoids creating duplicate security sections.

awk '
BEGIN {
    skip=0
}

/^[[:space:]]*\[security\][[:space:]]*$/ {
    skip=1
    next
}

/^[[:space:]]*\[/ {
    if (skip == 1) {
        skip=0
    }
}

{
    if (skip == 0) print
}
' "${DCV_CONFIG}" > "${DCV_CONFIG}.tmp"

mv "${DCV_CONFIG}.tmp" "${DCV_CONFIG}"

cat >> "${DCV_CONFIG}" <<'EOF'

[security]
authentication="system"
pam-service-name="dcv.custom"
EOF

echo "DCV security configuration:"
grep -A4 -B1 '^\[security\]' "${DCV_CONFIG}"

# ============================================================
# STEP 22 - VERIFY DCV SERVICE ACCOUNT
# ============================================================

echo ""
echo "============================================================"
echo "STEP 22 - VERIFYING DCV SERVICE ACCOUNT"
echo "============================================================"

if id dcv >/dev/null 2>&1; then

    echo "dcv service account exists."

else

    fail "dcv service account does not exist."

fi

# ============================================================
# STEP 23 - RESTART SSSD
#
# Required after allowed_uids / access_provider changes.
# ============================================================

echo ""
echo "============================================================"
echo "STEP 23 - RESTARTING SSSD"
echo "============================================================"

systemctl restart sssd || \
    fail "SSSD restart failed."

sleep 3

systemctl is-active --quiet sssd || \
    fail "SSSD is not active after restart."

# ============================================================
# STEP 24 - RESTART DCV
#
# Required to load:
#
#   authentication="system"
#   pam-service-name="dcv.custom"
# ============================================================

echo ""
echo "============================================================"
echo "STEP 24 - RESTARTING DCV SERVER"
echo "============================================================"

systemctl daemon-reload

systemctl enable dcvserver || \
    fail "Unable to enable dcvserver."

systemctl restart dcvserver || \
    fail "DCV server restart failed."

sleep 5

systemctl is-active --quiet dcvserver || \
    fail "DCV server is not active."

echo "DCV server is active."

# ============================================================
# STEP 25 - AD IDENTITY VALIDATION
# ============================================================

echo ""
echo "============================================================"
echo "STEP 25 - VALIDATING AD IDENTITY LOOKUP"
echo "============================================================"

echo "Testing identity lookup for ${AD_JOIN_USER}:"

if getent passwd "${AD_JOIN_USER}"; then

    echo "AD identity lookup successful."

else

    echo "WARNING:"
    echo "The AD join succeeded, but ${AD_JOIN_USER}"
    echo "was not returned by getent."
    echo "This should be investigated before production use."

fi

# ============================================================
# STEP 26 - VALIDATE SSSD SOCKET ACCESS
# ============================================================

echo ""
echo "============================================================"
echo "STEP 26 - VALIDATING SSSD"
echo "============================================================"

echo "SSSD status:"
systemctl --no-pager status sssd

echo ""
echo "SSSD configuration:"
cat /etc/sssd/sssd.conf

# ============================================================
# STEP 27 - FINAL DNS VALIDATION
# ============================================================

echo ""
echo "============================================================"
echo "STEP 27 - FINAL DNS VALIDATION"
echo "============================================================"

echo "AD domain:"
nslookup "${AD_DOMAIN}"

echo ""
echo "Kerberos SRV:"
dig +short SRV "_kerberos._tcp.${AD_DOMAIN}"

echo ""
echo "LDAP SRV:"
dig +short SRV "_ldap._tcp.${AD_DOMAIN}"

# ============================================================
# STEP 28 - FINAL DCV CONFIGURATION VALIDATION
# ============================================================

echo ""
echo "============================================================"
echo "STEP 28 - FINAL DCV VALIDATION"
echo "============================================================"

echo "DCV session manager:"
ls -l "${DCV_SESSION_MANAGER}"

echo "PAM file:"
ls -l "${DCV_PAM_FILE}"

echo ""
cat "${DCV_PAM_FILE}"

echo ""
echo "DCV security configuration:"
grep -A4 -B1 '^\[security\]' "${DCV_CONFIG}"

echo ""
echo "DCV service:"
systemctl --no-pager status dcvserver

# ============================================================
# STEP 29 - FINAL STATUS
# ============================================================

echo ""
echo "============================================================"
echo "STEP 29 - FINAL STATUS"
echo "============================================================"

echo "Hostname:"
hostname

echo ""
echo "Realm:"
realm list

echo ""
echo "SSSD:"
systemctl is-active sssd

echo ""
echo "DCV:"
systemctl is-active dcvserver

echo ""
echo "DNS:"
resolvectl status "${INTERFACE}"

# ============================================================
# SUCCESS
# ============================================================

printf 'SUCCESS\nCompleted: %s\n' "$(date)" > "${STATUS_FILE}"

chmod 600 "${STATUS_FILE}"

echo ""
echo "============================================================"
echo "RG AD + DCV AUTHENTICATION BOOTSTRAP COMPLETED"
echo "============================================================"
echo "Completed: $(date)"
echo ""
echo "Log:"
echo "  ${LOG_FILE}"
echo ""
echo "Status:"
echo "  ${STATUS_FILE}"
echo "============================================================"

exit 0